In [1]:
from astropy.table import Table
from astropy.io import fits
import numpy as np
import pylab as plt
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.optimize as fitter
%matplotlib inline

## 1)

In [34]:
def find_rows_with_all_odd(arr):
    odd_rows = []
    
    for i, row in enumerate(arr):
        if np.all(row % 2 != 0): 
            odd_rows.append(i)
    
    return odd_rows

arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
rows_with_all_odd = find_rows_with_all_odd(arr)

print("Rows with all odd numbers:", rows_with_all_odd)

Rows with all odd numbers: [1, 3]


## 2)

In [30]:
#2.1
def create_zero_matrix():
    return np.zeros((8, 8), dtype=int)

zero_matrix = create_zero_matrix()

print(zero_matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [36]:
#2.2
def create_alternating_matrix():
    matrix = np.zeros((8, 8), dtype=int)
    
    for i in range(0, 8, 2):  
        matrix[i] = [1 if j % 2 == 0 else 0 for j in range(8)]  
    
    return matrix

alternating_matrix = create_alternating_matrix()

print(alternating_matrix)

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [24]:
#2.3
def create_checkerboard_matrix():
    matrix = np.zeros((8, 8), dtype=int)
    
    for i in range(0, 8, 2):  
        matrix[i] = [1 if j % 2 == 0 else 0 for j in range(8)]  
    
    for i in range(1, 8, 2):  
        matrix[i] = [0 if j % 2 == 0 else 1 for j in range(8)]  
    
    return matrix

checkerboard_matrix = create_checkerboard_matrix()

print(checkerboard_matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [26]:
#2.4
def create_checkerboard_matrix():
    matrix = np.zeros((8, 8), dtype=int)
    
    
    for i in range(0, 8, 2):
        matrix[i] = [0 if j % 2 == 0 else 1 for j in range(8)]  
    
    for i in range(1, 8, 2):
        matrix[i] = [1 if j % 2 == 0 else 0 for j in range(8)]  
    
    return matrix

checkerboard_matrix = create_checkerboard_matrix()

print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 3)

In [38]:
def expand_string_with_spaces(s, num_spaces):
   
    space = ' ' * num_spaces
    
    expanded_string = space.join(s)
    
    return expanded_string

universe = np.array(['galaxy', 'clusters'])

expanded_universe = np.array([expand_string_with_spaces(word, 2) for word in universe])

print(expanded_universe)

['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


## 4)

In [43]:
def second_largest_in_columns(arr):
    
    second_largest_values = []
     
    for col in arr.T:  
        sorted_col = np.sort(col)  
        second_largest_values.append(sorted_col[-2])  
        
    return np.array(second_largest_values)

np.random.seed(42)  
arr = np.random.randint(1, 100, (5, 4))  

print("Original Array:")
print(arr)


result = second_largest_in_columns(arr)

print("Second-largest values in each column:")
print(result)

Original Array:
[[52 93 15 72]
 [61 21 83 87]
 [75 75 88 24]
 [ 3 22 53  2]
 [88 30 38  2]]
Second-largest values in each column:
[75 75 83 72]
